web:
  build: .
  ports:
    - "5000:5000"
  environment:
   - MONGODB_DATABASE=stats_db
   - MONGODB_USERNAME=root
   - MONGODB_PASSWORD=pass
   - MONGODB_HOSTNAME=mongodb
   - MONGODB_PORT=27017
  volumes:
    - .:/app
  links:
    - db
db:
  image: mongo:latest
  container_name: mongodb
  hostname: mongodb
  environment:
    - MONGO_INITDB_DATABASE=stats_db
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pass
    - MONGODB_DATA_DIR=/data/db
    - MONGODB_LOG_DIR=/data/log

  ports:
    - 27017:27017

# version: '3'
# services:
#     web:
#         build: .
#         command: flask run --host=0.0.0.0 --port=8000
#         ports:
#             - 8000:8000
#         environment:
#             - FLASK_APP=app.py
#         env_file:
#             - env.list
#         depends_on:
#             - db
#     db:
#         image: postgres
#         environment:
#             - POSTGRES_USER=salameh
#             - POSTGRES_PASSWORD=0012
#             - POSTGRES_DB=stats
#         volumes:
#             - flask_polls_data:/var/lib/postgresql/data

# volumes:
#     flask_polls_data: